### PR TITLE
fix: turned the core/THEMES into a default export

### PR DESCRIPTION
**Pull request by staranbeer**

### CODE REVIEW

**Comment by shubham-kaushal** [comment]
Hey @staranbeer, Thanks for the PR. Did you test the npm packages locally? If not then you can use this https://docs.npmjs.com/cli/v8/commands/npm-link

**Comment by staranbeer** [comment]
Hey @shubham-kaushal ! I used `npm publish --dry-run` and didn't get any issues. But since you want to change the `THEMES` to a default export that would result in many errors, should I also change the instances in which this module is being used as a named import. for example in the Alert.tsx file?

**Comment by shubham-kaushal** [comment]
> Hey @shubham-kaushal ! I used `npm publish --dry-run` and didn't get any issues. But since you want to change the `THEMES` to a default export that would result in many errors, should I also change the instances in which this module is being used as a named import. for example in the Alert.tsx file?

Hey @staranbeer Yes, sure. Also, try to test the import of the component in any of your local projects. You can also use verdaccio for the same.

**Instruction for testing import:**
After installing Jenga UI, you need to set up the `Root` at the root of your application. This can be either in your index.jsx, index.tsx or App.jsx depending on the framework you use.
```
import * as React from 'react'

// 1. import `Root` component
import { Root } from '@jengaui/react'

function App() {
  // 2. Wrap Root at the root of your app
  return (
    <Root>
      <TheRestOfYourApplication />
    </Root>
  )
}
```

**Comment by staranbeer** [comment]
@shubham-kaushal  I've changed the imports into default imports and I've set up the registry locally using verdaccio. After I imported the Button component from @jengaui/react. I am not getting any errors and this is the ouput. Is this the expected behavior?

image

**Comment by shubham-kaushal** [comment]
@staranbeer Rendered Button is looking fine. Did you try in the same workspace or outside the workspace (in a separate project) with verdaccio proxy package? And did you try with default export update?

**Comment by staranbeer** [comment]
@shubham-kaushal  I set up a registry proxy server using verdaccio and published the package to it after changing all instances to default export and then I installed it in another project and used it there. The only problem i faced in my project was that i had to downgrade my versions of react and react DOM to 17.0.2 for it to work because there was a dependency conflict between the library and react's latest version.

**Comment by shubham-kaushal** [comment]
Great, you can push the update with default export in this PR. We will support React 18 and the latest TS soon. We need some time to look into the typings related to the latest versions.

**Comment by staranbeer** [comment]
@shubham-kaushal There is a conflict between different eslint versions. The build is failing with this  error "ESLint: Plugin "react-hooks" was conflicted between ".eslintrc.json » eslint-config-next/core-web-vitals"

**Comment by shubham-kaushal** [comment]
> @shubham-kaushal There is a conflict between different eslint versions. The build is failing with this error "ESLint: Plugin "react-hooks" was conflicted between ".eslintrc.json » eslint-config-next/core-web-vitals"

Yes, there is an error with eslint but builds are failing because webpack failed to compile.

**Pull request merged**
